export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGINVALIDITY_FAIL = "LOGINVALIDITY_FAIL";
export const LOGOUT = "LOGOUT";

export const ADDEXPENSE_START = "ADDEXPENSE_START";
export const ADDEXPENSE_SUCCESS = "ADDEXPENSE_SUCCESS";
export const ADDEXPENSE_FAIL = "ADDEXPENSE_FAIl";

export const FILTER_START = "FILTER_START";
export const FILTER_END = "FILTER_END";
export const FILTER_ADD = "FILTER_ADD";